################ English language ##################
[en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
[jp]
languageName = "Jp"
languageCode = "jp-jp"
contentDir = "content/jp"
weight = 1
